### ISSUE TITLE
The disk is shown as not formatted

### ISSUE THREAD

**Issue by wbadry** [frankcohen/ReflectionsOS#13]

**Comment by wbadry** [comment]
HI,
I tried your code example :

https://github.com/frankcohen/ReflectionsOS/blob/main/Experiments/Flash_Drive_MSC_Nand_ESP32_SD/Flash_Drive_MSC_Nand_ESP32_SD.md

The SD card is correctly connected via SPI and on the SPI example, I can write and read with no issues.

When I use your code, I receive a message that the USB is not formatted. Also, would your code allow the data transfer like copy paste on the computer?

![1](https://github.com/frankcohen/ReflectionsOS/assets/5664750/0903aab5-f947-4646-9a09-8b4ca8eeb37a)

![2](https://github.com/frankcohen/ReflectionsOS/assets/5664750/0273be2c-975d-4ec6-8830-760475b16f2b)

Your help is much appreciated.

**Comment by frankcohen** [comment]
Hmmmmm… I haven’t tried the code on Windows. It works for me on a MacBook Pro running Sonoma 14.4.

Also, I’ve rewritten the code at least twice. I found bugs in the ESP MSC library. And I found multiple ways to use the ESP MSC library from various locations on the Web. It’s been frustrating.

Here is the my latest code (attached). Please let me know your experience with it.

-Frank


￼

**Comment by frankcohen** [comment]
Here is the attachment. -Frank
[NANDMSC.zip](https://github.com/frankcohen/ReflectionsOS/files/14686530/NANDMSC.zip)

**Comment by wbadry** [comment]
Thank you so much for your response. That fixed the issue.
