### ISSUE TITLE
Mass Storage Device example with SD_MMC (SDIO interface)

### ISSUE THREAD

**Issue by wbadry** [frankcohen/ReflectionsOS#14]
Hi,
Since your SPI Mass Storage Device code is beautifully working, are there any example you made for SDIO interface. I believe you already succeeded in making the USB part work. Have you had any trials with SDIO, as I intended to use it with eMMC.

Your assistance is much appreciated.

**Comment by wbadry** [comment]
Thanks @frankcohen so much. It is now applied in the latest [ESP32 Arduino Core 3.0.4][(libraries/SD_MMC/examples/SD2USBMSC/SD2USBMSC.ino](https://github.com/espressif/arduino-esp32/blob/master/libraries/SD_MMC/examples/SD2USBMSC/SD2USBMSC.ino))

**Comment by frankcohen** [comment]
Thank you.
