### ISSUE TITLE
Hello, some random questions...

### ISSUE THREAD

**Issue by RPdenBoer** [frankcohen/ReflectionsOS#6]
@frankcohen 
Hi, interesting project. Thanks for documenting it here.
I'm curious why you haven't used SD_MMC, rather than the slower SPI? I know ESP32 S2 doesn't have SDIO support, but S3 does so why not use it, even if only in 1 bit mode? Was this to support your choice of NAND chip? 
Speaking of which, you mentioned being able to store gigabytes of data, but the chip on your schematic seems to have a capacity of only 128MB, with a max of just 1GB in that family?

I'm working on some unrelated projects myself that have overlap on these issues, so interested to hear your thoughts :)

![1g](https://user-images.githubusercontent.com/94905251/200120841-803f199b-9c54-4887-b792-82b2b5f5a192.PNG)

**Comment by frankcohen** [comment]
Hi, I'm sorry for the too-late response. I chose SPI for easy coding. I started this project as a software engineer. It taught me all about hardware. I am getting 10-13 frames per second on a TFT display from the SPI Nand/SD. I'm now expecting to transition the design to MMC later this year. I have my hands full with the software coding for an exciting artful watch experience I am developing with Terri Hardin, Imagineer and Muppeteer, that uses the Reflections project. -Frank
